### ISSUE TITLE
Fatal Error: undefined method `text?' for nil:NilClass

### ISSUE THREAD

**Issue by CAMOBAP** [plurimath/mathml2asciimath#31]
https://github.com/metanorma/metanorma-cli/actions/runs/4542218735/jobs/8007261496#step:10:233

```
from C:/hostedtoolcache/windows/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/mathml2asciimath-0.0.14/lib/mathml2asciimath/m2a.rb:227:in `parse'
	from C:/hostedtoolcache/windows/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/mathml2asciimath-0.0.14/lib/mathml2asciimath/m2a.rb:170:in `block in join_parsed_children'
...
```

<details><summary>Full stack trace</summary>
<p>

```
C:/hostedtoolcache/windows/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/mathml2asciimath-0.0.14/lib/mathml2asciimath/m2a.rb:176:in `parse': undefined method `text?' for nil:NilClass (NoMethodError)
	from C:/hostedtoolcache/windows/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/mathml2asciimath-0.0.14/lib/mathml2asciimath/m2a.rb:227:in `parse'
	from C:/hostedtoolcache/windows/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/mathml2asciimath-0.0.14/lib/mathml2asciimath/m2a.rb:170:in `block in join_parsed_children'
	from C:/hostedtoolcache/windows/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/nokogiri-1.13.10-x64-mingw32/lib/nokogiri/xml/node_set.rb:234:in `block in each'
	from C:/hostedtoolcache/windows/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/nokogiri-1.13.10-x64-mingw32/lib/nokogiri/xml/node_set.rb:233:in `upto'
	from C:/hostedtoolcache/windows/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/nokogiri-1.13.10-x64-mingw32/lib/nokogiri/xml/node_set.rb:233:in `each'
	from C:/hostedtoolcache/windows/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/mathml2asciimath-0.0.14/lib/mathml2asciimath/m2a.rb:169:in `map'
	from C:/hostedtoolcache/windows/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/mathml2asciimath-0.0.14/lib/mathml2asciimath/m2a.rb:169:in `join_parsed_children'
	from C:/hostedtoolcache/windows/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/mathml2asciimath-0.0.14/lib/mathml2asciimath/m2a.rb:294:in `parse'
	from C:/hostedtoolcache/windows/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/mathml2asciimath-0.0.14/lib/mathml2asciimath/m2a.rb:170:in `block in join_parsed_children'
	from C:/hostedtoolcache/windows/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/nokogiri-1.13.10-x64-mingw32/lib/nokogiri/xml/node_set.rb:234:in `block in each'
	from C:/hostedtoolcache/windows/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/nokogiri-1.13.10-x64-mingw32/lib/nokogiri/xml/node_set.rb:233:in `upto'
	from C:/hostedtoolcache/windows/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/nokogiri-1.13.10-x64-mingw32/lib/nokogiri/xml/node_set.rb:233:in `each'
	from C:/hostedtoolcache/windows/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/mathml2asciimath-0.0.14/lib/mathml2asciimath/m2a.rb:169:in `map'
	from C:/hostedtoolcache/windows/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/mathml2asciimath-0.0.14/lib/mathml2asciimath/m2a.rb:169:in `join_parsed_children'
	from C:/hostedtoolcache/windows/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/mathml2asciimath-0.0.14/lib/mathml2asciimath/m2a.rb:182:in `parse'
	from C:/hostedtoolcache/windows/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/mathml2asciimath-0.0.14/lib/mathml2asciimath/m2a.rb:14:in `m2a'
	from C:/hostedtoolcache/windows/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/metanorma-standoc-2.4.1/lib/metanorma/standoc/cleanup_symbols.rb:22:in `block in asciimath_key'
	from C:/hostedtoolcache/windows/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/nokogiri-1.13.10-x64-mingw32/lib/nokogiri/xml/node.rb:1142:in `traverse'
	from C:/hostedtoolcache/windows/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/nokogiri-1.13.10-x64-mingw32/lib/nokogiri/xml/node.rb:1141:in `block in traverse'
	from C:/hostedtoolcache/windows/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/nokogiri-1.13.10-x64-mingw32/lib/nokogiri/xml/node_set.rb:234:in `block in each'
	from C:/hostedtoolcache/windows/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/nokogiri-1.13.10-x64-mingw32/lib/nokogiri/xml/node_set.rb:233:in `upto'
	from C:/hostedtoolcache/windows/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/nokogiri-1.13.10-x64-mingw32/lib/nokogiri/xml/node_set.rb:233:in `each'
	from C:/hostedtoolcache/windows/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/nokogiri-1.13.10-x64-mingw32/lib/nokogiri/xml/node.rb:1141:in `traverse'
	from C:/hostedtoolcache/windows/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/nokogiri-1.13.10-x64-mingw32/lib/nokogiri/xml/node.rb:1141:in `block in traverse'
	from C:/hostedtoolcache/windows/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/nokogiri-1.13.10-x64-mingw32/lib/nokogiri/xml/node_set.rb:234:in `block in each'
	from C:/hostedtoolcache/windows/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/nokogiri-1.13.10-x64-mingw32/lib/nokogiri/xml/node_set.rb:233:in `upto'
	from C:/hostedtoolcache/windows/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/nokogiri-1.13.10-x64-mingw32/lib/nokogiri/xml/node_set.rb:233:in `each'
	from C:/hostedtoolcache/windows/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/nokogiri-1.13.10-x64-mingw32/lib/nokogiri/xml/node.rb:1141:in `traverse'
	from C:/hostedtoolcache/windows/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/metanorma-standoc-2.4.1/lib/metanorma/standoc/cleanup_symbols.rb:19:in `asciimath_key'
	from C:/hostedtoolcache/windows/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/metanorma-standoc-2.4.1/lib/metanorma/standoc/cleanup_symbols.rb:9:in `symbol_key'
	from C:/hostedtoolcache/windows/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/metanorma-standoc-2.4.1/lib/metanorma/standoc/cleanup_symbols.rb:40:in `block in extract_symbols_list'
	from C:/hostedtoolcache/windows/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/nokogiri-1.13.10-x64-mingw32/lib/nokogiri/xml/node_set.rb:234:in `block in each'
	from C:/hostedtoolcache/windows/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/nokogiri-1.13.10-x64-mingw32/lib/nokogiri/xml/node_set.rb:233:in `upto'
	from C:/hostedtoolcache/windows/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/nokogiri-1.13.10-x64-mingw32/lib/nokogiri/xml/node_set.rb:233:in `each'
	from C:/hostedtoolcache/windows/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/metanorma-standoc-2.4.1/lib/metanorma/standoc/cleanup_symbols.rb:38:in `extract_symbols_list'
	from C:/hostedtoolcache/windows/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/metanorma-standoc-2.4.1/lib/metanorma/standoc/cleanup_symbols.rb:50:in `block in symbols_cleanup'
	from C:/hostedtoolcache/windows/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/nokogiri-1.13.10-x64-mingw32/lib/nokogiri/xml/node_set.rb:234:in `block in each'
	from C:/hostedtoolcache/windows/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/nokogiri-1.13.10-x64-mingw32/lib/nokogiri/xml/node_set.rb:233:in `upto'
	from C:/hostedtoolcache/windows/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/nokogiri-1.13.10-x64-mingw32/lib/nokogiri/xml/node_set.rb:233:in `each'
	from C:/hostedtoolcache/windows/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/metanorma-standoc-2.4.1/lib/metanorma/standoc/cleanup_symbols.rb:49:in `symbols_cleanup'
	from C:/hostedtoolcache/windows/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/metanorma-standoc-2.4.1/lib/metanorma/standoc/cleanup.rb:50:in `cleanup'
	from C:/hostedtoolcache/windows/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/metanorma-nist-2.2.7/lib/metanorma/nist/cleanup.rb:7:in `cleanup'
	from C:/hostedtoolcache/windows/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/metanorma-standoc-2.4.1/lib/metanorma/standoc/base.rb:197:in `makexml'
	from C:/hostedtoolcache/windows/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/metanorma-nist-2.2.7/lib/metanorma/nist/converter.rb:91:in `makexml'
	from C:/hostedtoolcache/windows/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/metanorma-standoc-2.4.1/lib/metanorma/standoc/base.rb:148:in `document1'
	from C:/hostedtoolcache/windows/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/metanorma-standoc-2.4.1/lib/metanorma/standoc/base.rb:137:in `document'
	from C:/hostedtoolcache/windows/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/metanorma-standoc-2.4.1/lib/metanorma/standoc/utils.rb:13:in `convert'
	from C:/hostedtoolcache/windows/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/asciidoctor-2.0.18/lib/asciidoctor/document.rb:956:in `convert'
	from C:/hostedtoolcache/windows/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/asciidoctor-2.0.18/lib/asciidoctor/convert.rb:120:in `convert'
	from C:/hostedtoolcache/windows/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/metanorma-1.5.8/lib/metanorma/input/asciidoc.rb:18:in `process'
	from C:/hostedtoolcache/windows/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/metanorma-1.5.8/lib/metanorma/processor.rb:21:in `input_to_isodoc'
	from C:/hostedtoolcache/windows/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/metanorma-1.5.8/lib/metanorma/compile.rb:60:in `process_input_adoc'
	from C:/hostedtoolcache/windows/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/metanorma-1.5.8/lib/metanorma/compile.rb:42:in `process_input'
	from C:/hostedtoolcache/windows/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/metanorma-1.5.8/lib/metanorma/compile.rb:33:in `compile'
	from D:/a/metanorma-cli/metanorma-cli/lib/metanorma/cli/compiler.rb:45:in `compile_file'
	from D:/a/metanorma-cli/metanorma-cli/lib/metanorma/cli/compiler.rb:30:in `compile'
	from D:/a/metanorma-cli/metanorma-cli/lib/metanorma/cli/compiler.rb:35:in `compile'
	from D:/a/metanorma-cli/metanorma-cli/lib/metanorma/cli/site_generator.rb:91:in `compile'
	from D:/a/metanorma-cli/metanorma-cli/lib/metanorma/cli/site_generator.rb:31:in `block in generate'
	from D:/a/metanorma-cli/metanorma-cli/lib/metanorma/cli/site_generator.rb:31:in `each'
	from D:/a/metanorma-cli/metanorma-cli/lib/metanorma/cli/site_generator.rb:31:in `generate'
	from D:/a/metanorma-cli/metanorma-cli/lib/metanorma/cli/site_generator.rb:26:in `generate'
	from D:/a/metanorma-cli/metanorma-cli/lib/metanorma/cli/commands/site.rb:33:in `generate'
	from C:/hostedtoolcache/windows/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	from C:/hostedtoolcache/windows/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/thor-hollaback-0.2.1/lib/thor/hollaback.rb:68:in `run'
	from C:/hostedtoolcache/windows/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	from C:/hostedtoolcache/windows/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	from C:/hostedtoolcache/windows/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:116:in `invoke'
	from C:/hostedtoolcache/windows/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor.rb:243:in `block in subcommand'
	from C:/hostedtoolcache/windows/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	from C:/hostedtoolcache/windows/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/thor-hollaback-0.2.1/lib/thor/hollaback.rb:68:in `run'
	from C:/hostedtoolcache/windows/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	from C:/hostedtoolcache/windows/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	from C:/hostedtoolcache/windows/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
	from D:/a/metanorma-cli/metanorma-cli/lib/metanorma/cli.rb:34:in `start'
	from D:/a/metanorma-cli/metanorma-cli/exe/metanorma:25:in `block in <top (required)>'
	from D:/a/metanorma-cli/metanorma-cli/exe/metanorma:43:in `<top (required)>'
	from C:/hostedtoolcache/windows/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/bin/metanorma:23:in `load'
	from C:/hostedtoolcache/windows/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/bin/metanorma:23:in `<main>'
```

</p>
</details>

> * Logs are for windows but the issue happens on all three platofirms

**Comment by opoudjis** [comment]
I don't know what is happening, but I know what I'm doing to solve it: removing this gem and substituting it with Plurimath.

**Comment by opoudjis** [comment]
@CAMOBAP I don't monitor Plurimath the way I monitor the Metanorma project board; if you want me to notice something earlier, please ensure it ends up on the Metanorma project board.

**Comment by opoudjis** [comment]
Crash goes away
